language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: h+Yw3mF/Q4NTuNNodGr0W+0X4qDRNWtORXF7BU6nqn1SjwB0VuW2Z0kidTRQCeDLoOJKt/zgEK22Wk2xC1WOYOKmJGTqVsAtdnJ7uuEUZ4EwRbCOVBKwNTh8D7bcQ1PyWTDC5w/gxlqxMbJ8axTiBZGpgALSZgOxbcWejvxQbS6SGgtpARqoBwOVX2n5k/7KcX1/etJdXI3IeTpkZj/PkqcAIfBGwChzJ9jDzDPZXrz15829hueGRzOCbQSunfgVsmfrarPWSulHySYYyY+xEyovOz25Otm9k/9TDTH888oDnz7E1fX9r3xUsU/aP+kfRQXipGRSlswJPsqnhWn1Po2IYjqrGDmVyg80c1n4hsbS8yxAEV/Mzay6HaRrjJwXKmSKZGNqwnwxlFAiWdyRkQvthxSNHlcy29YVOaP27iIqVzxSHEHMXFs2GI41T8YWPT+TjYdK8L0HYYdienceaznfuCzAK+bfNPcfqb2wCEYx0XDIYAgf2uA0ZCDmxj4WoMze56K013nggF2z/7T7ck0G32/BCoiEtmfFg8uKB9MtT8sCGK96GBwalec80gb6rlI3x8eWk/ITF97QFKXKoQxyZSIeGO5l1qcumulQxVFIVbh1sY7NQbSswYXZ3o4EjloDrr9jCAen0mLRDJjHnk6obSJesudm3X3Q7R0F5Ow=
  app: meto
  on:
    repo: samuelufabc/meto
  skip_cleanup: 'true'
