language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: j0Ep1eTLZjOQlB3gsdadyPDCQa5oIyDSL2q7Qmm3N+w5EMzHbVNu4HReNgODKgaSppoSfuWmbGJOEygvCxvkNVTCBefnMP64uL+IlAvYepFSs/5BfEw7Ljs9mLLiKPn8P6RobYmG/rWGVqV8srLxskZj5B6Em4RKYqpAjGjprb2XK56v0iKTccXBfVZhHVmxLFfUxIJCUqYsl5nG40J+Nql04T/yWLQPSrGdW5lQBJ7rxddRXz6mDWmjQY46VSuv0EwioZEnlVXtfNrD0zdMBSJO8Flan41P7Tba1YP22Ml6b2w2g6pzmkRON89A8bjpXNyMOtNsOZKeaZHwQl+Cy2QfvTkcp6JHLt8jOHDb5qztvX6PRBNkW0MhmWl0aJw7MsoFSVoA8QzM3DgDKDsb8MD3cZOfjIBO2pTDxG1N06NfCPW+0IDspR8xokKNMj2TOL+pFTFJMGx4ZT5tc+Go4EggfsJPsWG96cyxdZr2FIl8Ug+NVDWu8L/3y4XsjSR6pST9Roh9KrLxdy3FiEKh+BCo2H9WpZQ/k0U3ECWgiQDpCFwNxwNWG/eqqO3ISPOG6P+y4ybEqtlm3XEVxCBFqEj/mOQh7pcdJQEvPylqTDVIJfZwnVVXD/TXtEC9BmSDwgBvNUHI1GokihJfVvFJr9XTZ7Cv4BxJVk8AwrGvehE=
  app: meto
  on:
    repo: samuelufabc/meto
  skip_cleanup: 'true'
