language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: bn3BO2B17r7jzJZDO9gk6UTLLDDbcgzxARK5RXMmB1PWsoVLbddQENLZRndOzrW/j7Lth+tssZQKvl5HAsxVWkCh/unI6EuTEXSNKGtM68odNqpMUAd7YqApCkMpFLKSx+i+Avva+Q7yGAlJRxmhaBQ7WX+evXWrOju3M2YC6Ty2kehpilsjkWI351dldHmMqFAFxcoclnq44jknUkRuVCy8AATksRXaJOyLl6TAex8qUBq0MK99upzmtIIY6QCGSi7sImF+vD3ghRTYZr82Ya02mlB1Jn8JoDDrAMFyz7e2D2Wnq9t5IC+ShCHvIVvNikCj++MMvDX3TgHF9KcJ1idXpq2iMlkIkVt2amnKolRS34rgXO9bge4IxDg7LuO+EBwgNHhvLN6ZMUCIrqju+EC6kn9swW5s5WbkOjhrbcWXIg0i/26cmWpURjBVWCKjk6850u3UfT8SW9e1i4gIWvHX8q0+0DNJe8A5GtZO8z1PPw1GQM+JDgN9ARbyMg9hhJVwVeubx780X6aB+41IT8TmzaMJDWJpCDJu19lyKBO6dVe5uKxmOd/WOjbR+6bjOD08Qk0w/4DV93lmnBJ8M50CfA0DE6zNht7ISw24II5KvEvjubmWGkEaHe9NFmxs+z5qQJVnqoAwYlMYD0IfEYwbyQc6FO1U9KjYih21t4Q=
  app: metosamuka
  on:
    repo: samuelufabc/meto
  skip_cleanup: 'true'
env:
  global:
    secure: eNeqAbCj67DuQG7XI30wHYd9e5ZlR6GFtTYp42GeO+QHnhZd8FoIWsPoc8oY29ojO8nCBjGHhirQwS5izCDa8AwvYpRchIkGp5t8wXDpFpIlKhy8IYxtfyn/L66+1zS5RZWanofb4GfQ2MnlVWXN4KzcHqYFS1pLro0a4crQ84p3IsH1oG7DRalwQEJOxnSPS4kDu8uFcSKjOj5Tx9D5EocT7oqZB67jaUG3T01SpQteWJ9uyUe4mdI5tulcrpYjbwCg+xBQEMOxVrP6ZtqtJou8n3GOlcFfNXJ4iMdHzhFTAuyCAAUNKClLnscXngE+UgAJMDRfMno0OHmiQUWFFOEQqRCDI3uqqBVpiVCEo9nGTFEJXsLArfB+12bE/1/HX8+J2qxf1E9llI3Rlf5zHZLcl2QOLIqvWSgM3NbFbwtvLP8XRcgY6MLFInQ8U9X+UnysO3h3JFuJPAd55vuA445dsHCZ6Ye9jRW20KOXh4Ln2E/w4qSpkBHfDTC+9fTaTBnwEH5Bd4CoktBEHJraD+0TXFRB3ifcAtL/Dw25T3UO8VIeRVmCbDumPT72Fcc+Mv7wgOHfaWhNBLSnmp06Ctdfne8+OyWpt5gS1m5ghmI5y8/0peXzHRHYm8XJEZ5vyh7pmWkLmSL3CGXPmt9N6v5tcwCG3M9tCYGfZv9oPW4=
