language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: tgukOVIUZfoRu59i6Gooqy3E4pAJo6/JR+xcWXVR7q6AbKKSVkdY1dPaeBMyhMZ6Gikm8Usxm8z7q22MnJs2TO7lFym1pPzKEZBLfS7JEXjImRlAJ+HDG2y2L8JOhGGAcBkAO8MeSmCtlcHam4jTpr9m9Z1n6MAM7MsD273cPhpxjV2axElLz2B2QEgyk7ljR6wtECzBnBvqpue+//e2gEINtY3EaKNE02b/1x4rtxyPC1+ZXz/WsRKFcPEhtw5oWhEuOQk69sn7VjUMuB5suhKg71bfFfn0HB2Ya3DNa4q+ExgI8C06i3/3BSEbHMDOHTCLX8USO8KptdvjOSz09ucN6fYlVOsoEsNO9V1avXrLIPDXmcf4DAXUnoE6qTRCdDu/oZ2+kdD+60wp48E3JIbUDa9RP+A63RHrbjm1qQ7zZwbBN3Z5xOV3lF1YeO29Fi2KyjFGSp0HKaN+j8+Fm/eI4VW/vHd6NagR4xL06bPvBZCYPVseUkhIn1Kc7PE8qoHB3gKMOl9WiF5CaBNEZLmH1OeKEVtWG+b0uRjbbIRqKJo4QWcKXZC3+Kg7NVjCJ6stIlmGal+uTs4/qaeLIgVwopueuc5oZPssj1otiJxq5aTfJGPcd5fixUl8xp/fvA0rbFIO4IIM0tV7IGJHeGbPitt1oIPqI4a10pgEE/s=
