language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: p0nviyyxUtp18CiR1C/EL8+OcHaj8ljyO4Yd6YGOgEKTrhyiitVWvJ0DCgL/24AR8sOUGEWAtqPq6CgtXhhwTZdJDh819xCYf25H0DzfrKZvghXDPaW/UVsrSTpR0S75u0csBBq5rxQCkvmoLrZsk0IESg0o66R8uy/2Sh8khayN2Djvqof+MK+cOI9h0bsb1NaJlcejzAOrIPt5kMhLwliIdFPClLxM5L2rOpFUb0QCun4aozFl2pV6u73NWvIrA2YKzlg0RgGVwdSbW+bFhtrsI2rK1+v+BWKRJe0I+W4TaWKxxyEyacyePkwOVgKcJ3guEtWeucjYkaMpPjfSj45cnciiiaefkkyEOvMZzVNcrsFT1A6vkzMjHZwE3gs7xHfHSHXOQvcS8QXG+U/TKLJDC7agKnQrmT0GfOhfmUbQv3eBbkSe9k5P35/bZjTV74zpCj97wTsmjifEN+uHL0apBUaY++fR1nVbBlfiztmAll13QGwypqrnQjPnZPp5JCWTrgn8rjzC1ggtiYb1DaLC2HBnqEzxoDesbrRDqK8NP5Gce6As9E30RBczyhnIwnVJMlFWRIvLjhUYpx91bW+S6b12QYCFa48SPA/3sRzFcaPsF1vDSzomW6YfDycIQMJN+7VkLJ8SRYlfanUyQJnTt3gvKlssIae5WGC6Oxs=
  app: meto
  on:
    repo: samuelufabc/meto
  skip_cleanup: 'true'
